# Generated by Django 6.0.2 on 2026-02-08 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(help_text='Recipient email address', max_length=255, validators=[django.core.validators.EmailValidator(message='Email should be valid')])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when email was sent')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^[0-9]{10}$')])),
                ('message', models.TextField(help_text='SMS message content', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when SMS was sent')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'sms_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^[0-9]{10}$')])),
                ('message', models.TextField(help_text='WhatsApp message content', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when WhatsApp message was sent')),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'db_table': 'whatsapp_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
